# Generated by Django 4.2.17 on 2024-12-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='tax_rate',
        ),
    ]
