# Generated by Django 4.2.17 on 2024-12-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesorder', '0002_remove_salesorder_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
