# Generated by Django 4.2.17 on 2024-12-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesorder', '0003_alter_salesorderitem_price_at_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='status',
        ),
    ]
