# Generated by Django 4.2.16 on 2024-12-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productstocklog_user'),
        ('salesorder', '0004_remove_salesorder_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesOrderItem',
            new_name='Cart',
        ),
    ]
