# Generated by Django 4.2.17 on 2024-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productstocklog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productstocklog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
